### ISSUE TITLE
Udp server with a connection manager based on Json

### ISSUE THREAD

**Issue by HaMeRoNy** [Sietseq/NodeJS-Game-Server#1]
Hello.
I found you because you made a udp server with a connection manager. I recently started learning UDP on node.js
I did not find information on connection managers for dgram. Since it is connectionless.
But my game client is gamemaker. Could you help me to make the same server only based on Json?
I've been trying to find a solution for over a 2 week now. Please help me do this. We can discuss it on Discord if it's more convenient for you. 
In addition, I think the Gamemaker community will be very happy with such a tamplate, we cane put it for public repositorie. just like you do with your godot server. I can make the client side for the server .

**Comment by Sietseq** [comment]
The connection manager works by sending heartbeat packets to check if the client is still alive.
https://en.wikipedia.org/wiki/Heartbeat_(computing)

If you have any further questions, or you would like to still work together on this my Discord is: Sietse#4808
The project you are talking about is definitely something I'm interested in.
